services:
  - type: web
    name: cloudmart-backend
    env: python
    buildCommand: ./backend/build.sh
    startCommand: cd backend && python -m gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: cloudmart-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'false'

databases:
  - name: cloudmart-db
    databaseName: cloudmart
    user: cloudmart_user
